### ISSUE TITLE
run `downloadedData <- hpaDownload(downloadList='all')` error

### ISSUE THREAD

**Issue by wangdepin** [trannhatanh89/HPAanalyze#18]
when run `downloadedData <- hpaDownload(downloadList='all')`, it happens error.

![image](https://user-images.githubusercontent.com/38637596/227890322-bd8cdd86-93a7-4a89-a3c3-7e193750662b.png)

**Comment by anhtr** [comment]
Hi @wangdepin, thank you for filing this issue. Can you tell me which version of HPAanalyze you are using? rna_blood_cell.tsv.zip is no longer available from HPA v22.0. Please update your packages to the newest version to ensure that everything works properly.
