### ISSUE TITLE
Query: hpaDownload file location

### ISSUE THREAD

**Issue by SuhasSrinivasan** [trannhatanh89/HPAanalyze#24]
Hi,

Thank you for developing and maintaining this useful package!

A query:
When using the `hpaDownload()` where are the downloaded files stored?
Also, are these files removed automatically after the R session is quit/restarted?

**Comment by anhtr** [comment]
Hello @SuhasSrinivasan. The raw files downloaded from HPA are treated as temp files and will not be kept, as they are not relevant to the functions of this package. If you want to get those file for safe keeping or other purposes, you can download them straight from the source at https://www.proteinatlas.org/about/download.
