### ISSUE TITLE
Feature Request: Print hpaDownload() file location

### ISSUE THREAD

**Issue by SuhasSrinivasan** [trannhatanh89/HPAanalyze#25]
Hi,

Thank you for developing and maintaining this useful package!

When using the `hpaDownload()` there is a download progress bar, however it is not clear where these files are stored and what happens to them after R session exit.

It will be very helpful to print the directory/cache where these HPA files are stored.

**Comment by anhtr** [comment]
Hello @SuhasSrinivasan, `hpaDownload` is a convenient way to make data frames from HPA downloadable data. Keeping the raw data files is out of the scope of this package. You can always get them directly from the [source](https://www.proteinatlas.org/about/download).
