### ISSUE TITLE
Feature Request: hpaDownload() use already downloaded files

### ISSUE THREAD

**Issue by SuhasSrinivasan** [trannhatanh89/HPAanalyze#26]
Hi,

Thank you for developing and maintaining this useful package!

When using `hpaDownload()` the files are downloaded for **_each_** function call.
It would be quite helpful if already downloaded files can be reused, and if there is a parameter to pass the directory.
This would require information from request #25

**Comment by anhtr** [comment]
Hello @SuhasSrinivasan, this would introduce the complications of aligning the version of the data and of the function. HPA downloadable data can have different column names and file names in each version. In the past we tried to support earlier versions, but it had proven to be too complicated and niche. For reproducibility purpose, consider saving the list of data frames that `hpaDownload` creates as .rds or the individual data frames as .rds, or .csv.
